version: "3.7"
services:

  app:
    build: .
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_PASSWORD=password
